// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/plugin/v1/plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemotePluginService_Ping_FullMethodName            = "/plugin.v1.RemotePluginService/Ping"
	RemotePluginService_ListPlugins_FullMethodName     = "/plugin.v1.RemotePluginService/ListPlugins"
	RemotePluginService_CreateInstance_FullMethodName  = "/plugin.v1.RemotePluginService/CreateInstance"
	RemotePluginService_DestroyInstance_FullMethodName = "/plugin.v1.RemotePluginService/DestroyInstance"
	RemotePluginService_RunInstance_FullMethodName     = "/plugin.v1.RemotePluginService/RunInstance"
)

// RemotePluginServiceClient is the client API for RemotePluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RemotePluginService is implemented by a remote plugin server.
type RemotePluginServiceClient interface {
	// Ping is a lightweight unary heartbeat request.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// ListPlugins returns plugin metadata exposed by the remote plugin server.
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// CreateInstance creates one plugin instance for a workflow node/session.
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// DestroyInstance releases a previously created plugin instance.
	DestroyInstance(ctx context.Context, in *DestroyInstanceRequest, opts ...grpc.CallOption) (*DestroyInstanceResponse, error)
	// RunInstance is the dedicated bidirectional event stream for one plugin instance.
	RunInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RuntimeMessage, RuntimeMessage], error)
}

type remotePluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemotePluginServiceClient(cc grpc.ClientConnInterface) RemotePluginServiceClient {
	return &remotePluginServiceClient{cc}
}

func (c *remotePluginServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RemotePluginService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePluginServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, RemotePluginService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePluginServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, RemotePluginService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePluginServiceClient) DestroyInstance(ctx context.Context, in *DestroyInstanceRequest, opts ...grpc.CallOption) (*DestroyInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyInstanceResponse)
	err := c.cc.Invoke(ctx, RemotePluginService_DestroyInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePluginServiceClient) RunInstance(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RuntimeMessage, RuntimeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemotePluginService_ServiceDesc.Streams[0], RemotePluginService_RunInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RuntimeMessage, RuntimeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemotePluginService_RunInstanceClient = grpc.BidiStreamingClient[RuntimeMessage, RuntimeMessage]

// RemotePluginServiceServer is the server API for RemotePluginService service.
// All implementations must embed UnimplementedRemotePluginServiceServer
// for forward compatibility.
//
// RemotePluginService is implemented by a remote plugin server.
type RemotePluginServiceServer interface {
	// Ping is a lightweight unary heartbeat request.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// ListPlugins returns plugin metadata exposed by the remote plugin server.
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// CreateInstance creates one plugin instance for a workflow node/session.
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// DestroyInstance releases a previously created plugin instance.
	DestroyInstance(context.Context, *DestroyInstanceRequest) (*DestroyInstanceResponse, error)
	// RunInstance is the dedicated bidirectional event stream for one plugin instance.
	RunInstance(grpc.BidiStreamingServer[RuntimeMessage, RuntimeMessage]) error
	mustEmbedUnimplementedRemotePluginServiceServer()
}

// UnimplementedRemotePluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemotePluginServiceServer struct{}

func (UnimplementedRemotePluginServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRemotePluginServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedRemotePluginServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedRemotePluginServiceServer) DestroyInstance(context.Context, *DestroyInstanceRequest) (*DestroyInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyInstance not implemented")
}
func (UnimplementedRemotePluginServiceServer) RunInstance(grpc.BidiStreamingServer[RuntimeMessage, RuntimeMessage]) error {
	return status.Error(codes.Unimplemented, "method RunInstance not implemented")
}
func (UnimplementedRemotePluginServiceServer) mustEmbedUnimplementedRemotePluginServiceServer() {}
func (UnimplementedRemotePluginServiceServer) testEmbeddedByValue()                             {}

// UnsafeRemotePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemotePluginServiceServer will
// result in compilation errors.
type UnsafeRemotePluginServiceServer interface {
	mustEmbedUnimplementedRemotePluginServiceServer()
}

func RegisterRemotePluginServiceServer(s grpc.ServiceRegistrar, srv RemotePluginServiceServer) {
	// If the following call panics, it indicates UnimplementedRemotePluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemotePluginService_ServiceDesc, srv)
}

func _RemotePluginService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePluginServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePluginService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePluginServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePluginService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePluginServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePluginService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePluginServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePluginService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePluginServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePluginService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePluginServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePluginService_DestroyInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePluginServiceServer).DestroyInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePluginService_DestroyInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePluginServiceServer).DestroyInstance(ctx, req.(*DestroyInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePluginService_RunInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemotePluginServiceServer).RunInstance(&grpc.GenericServerStream[RuntimeMessage, RuntimeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemotePluginService_RunInstanceServer = grpc.BidiStreamingServer[RuntimeMessage, RuntimeMessage]

// RemotePluginService_ServiceDesc is the grpc.ServiceDesc for RemotePluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemotePluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.RemotePluginService",
	HandlerType: (*RemotePluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RemotePluginService_Ping_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _RemotePluginService_ListPlugins_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _RemotePluginService_CreateInstance_Handler,
		},
		{
			MethodName: "DestroyInstance",
			Handler:    _RemotePluginService_DestroyInstance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunInstance",
			Handler:       _RemotePluginService_RunInstance_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/plugin/v1/plugin.proto",
}
