// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/plugin/v1/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DropStrategy int32

const (
	DropStrategy_DROP_STRATEGY_UNSPECIFIED   DropStrategy = 0
	DropStrategy_DROP_STRATEGY_BLOCK_IF_FULL DropStrategy = 1
	DropStrategy_DROP_STRATEGY_DROP_NEWEST   DropStrategy = 2
	DropStrategy_DROP_STRATEGY_DROP_OLDEST   DropStrategy = 3
)

// Enum value maps for DropStrategy.
var (
	DropStrategy_name = map[int32]string{
		0: "DROP_STRATEGY_UNSPECIFIED",
		1: "DROP_STRATEGY_BLOCK_IF_FULL",
		2: "DROP_STRATEGY_DROP_NEWEST",
		3: "DROP_STRATEGY_DROP_OLDEST",
	}
	DropStrategy_value = map[string]int32{
		"DROP_STRATEGY_UNSPECIFIED":   0,
		"DROP_STRATEGY_BLOCK_IF_FULL": 1,
		"DROP_STRATEGY_DROP_NEWEST":   2,
		"DROP_STRATEGY_DROP_OLDEST":   3,
	}
)

func (x DropStrategy) Enum() *DropStrategy {
	p := new(DropStrategy)
	*p = x
	return p
}

func (x DropStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DropStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (DropStrategy) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[0]
}

func (x DropStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DropStrategy.Descriptor instead.
func (DropStrategy) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_SIGNAL      EventType = 1
	EventType_EVENT_TYPE_PAYLOAD     EventType = 2
	EventType_EVENT_TYPE_AUDIO       EventType = 3
	EventType_EVENT_TYPE_VIDEO       EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SIGNAL",
		2: "EVENT_TYPE_PAYLOAD",
		3: "EVENT_TYPE_AUDIO",
		4: "EVENT_TYPE_VIDEO",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_SIGNAL":      1,
		"EVENT_TYPE_PAYLOAD":     2,
		"EVENT_TYPE_AUDIO":       3,
		"EVENT_TYPE_VIDEO":       4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type ValueType int32

const (
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	ValueType_VALUE_TYPE_STRING      ValueType = 1
	ValueType_VALUE_TYPE_NUMBER      ValueType = 2
	ValueType_VALUE_TYPE_INTEGER     ValueType = 3
	ValueType_VALUE_TYPE_BOOLEAN     ValueType = 4
	ValueType_VALUE_TYPE_OBJECT      ValueType = 5
	ValueType_VALUE_TYPE_ARRAY       ValueType = 6
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNSPECIFIED",
		1: "VALUE_TYPE_STRING",
		2: "VALUE_TYPE_NUMBER",
		3: "VALUE_TYPE_INTEGER",
		4: "VALUE_TYPE_BOOLEAN",
		5: "VALUE_TYPE_OBJECT",
		6: "VALUE_TYPE_ARRAY",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"VALUE_TYPE_STRING":      1,
		"VALUE_TYPE_NUMBER":      2,
		"VALUE_TYPE_INTEGER":     3,
		"VALUE_TYPE_BOOLEAN":     4,
		"VALUE_TYPE_OBJECT":      5,
		"VALUE_TYPE_ARRAY":       6,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[2]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type RuntimeMessageType int32

const (
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_UNSPECIFIED  RuntimeMessageType = 0
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_LIFECYCLE    RuntimeMessageType = 1
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_SIGNAL       RuntimeMessageType = 2
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_PAYLOAD      RuntimeMessageType = 3
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_EMIT_SIGNAL  RuntimeMessageType = 4
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_EMIT_PAYLOAD RuntimeMessageType = 5
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_EMIT_LOG     RuntimeMessageType = 6
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_ACK          RuntimeMessageType = 7
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_REPORT       RuntimeMessageType = 8
	RuntimeMessageType_RUNTIME_MESSAGE_TYPE_CANCEL       RuntimeMessageType = 9
)

// Enum value maps for RuntimeMessageType.
var (
	RuntimeMessageType_name = map[int32]string{
		0: "RUNTIME_MESSAGE_TYPE_UNSPECIFIED",
		1: "RUNTIME_MESSAGE_TYPE_LIFECYCLE",
		2: "RUNTIME_MESSAGE_TYPE_SIGNAL",
		3: "RUNTIME_MESSAGE_TYPE_PAYLOAD",
		4: "RUNTIME_MESSAGE_TYPE_EMIT_SIGNAL",
		5: "RUNTIME_MESSAGE_TYPE_EMIT_PAYLOAD",
		6: "RUNTIME_MESSAGE_TYPE_EMIT_LOG",
		7: "RUNTIME_MESSAGE_TYPE_ACK",
		8: "RUNTIME_MESSAGE_TYPE_REPORT",
		9: "RUNTIME_MESSAGE_TYPE_CANCEL",
	}
	RuntimeMessageType_value = map[string]int32{
		"RUNTIME_MESSAGE_TYPE_UNSPECIFIED":  0,
		"RUNTIME_MESSAGE_TYPE_LIFECYCLE":    1,
		"RUNTIME_MESSAGE_TYPE_SIGNAL":       2,
		"RUNTIME_MESSAGE_TYPE_PAYLOAD":      3,
		"RUNTIME_MESSAGE_TYPE_EMIT_SIGNAL":  4,
		"RUNTIME_MESSAGE_TYPE_EMIT_PAYLOAD": 5,
		"RUNTIME_MESSAGE_TYPE_EMIT_LOG":     6,
		"RUNTIME_MESSAGE_TYPE_ACK":          7,
		"RUNTIME_MESSAGE_TYPE_REPORT":       8,
		"RUNTIME_MESSAGE_TYPE_CANCEL":       9,
	}
)

func (x RuntimeMessageType) Enum() *RuntimeMessageType {
	p := new(RuntimeMessageType)
	*p = x
	return p
}

func (x RuntimeMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (RuntimeMessageType) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[3]
}

func (x RuntimeMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeMessageType.Descriptor instead.
func (RuntimeMessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type LifecycleType int32

const (
	LifecycleType_LIFECYCLE_TYPE_UNSPECIFIED LifecycleType = 0
	LifecycleType_LIFECYCLE_TYPE_START       LifecycleType = 1
	LifecycleType_LIFECYCLE_TYPE_READY       LifecycleType = 2
	LifecycleType_LIFECYCLE_TYPE_PAUSE       LifecycleType = 3
	LifecycleType_LIFECYCLE_TYPE_RESUME      LifecycleType = 4
	LifecycleType_LIFECYCLE_TYPE_STOP        LifecycleType = 5
)

// Enum value maps for LifecycleType.
var (
	LifecycleType_name = map[int32]string{
		0: "LIFECYCLE_TYPE_UNSPECIFIED",
		1: "LIFECYCLE_TYPE_START",
		2: "LIFECYCLE_TYPE_READY",
		3: "LIFECYCLE_TYPE_PAUSE",
		4: "LIFECYCLE_TYPE_RESUME",
		5: "LIFECYCLE_TYPE_STOP",
	}
	LifecycleType_value = map[string]int32{
		"LIFECYCLE_TYPE_UNSPECIFIED": 0,
		"LIFECYCLE_TYPE_START":       1,
		"LIFECYCLE_TYPE_READY":       2,
		"LIFECYCLE_TYPE_PAUSE":       3,
		"LIFECYCLE_TYPE_RESUME":      4,
		"LIFECYCLE_TYPE_STOP":        5,
	}
)

func (x LifecycleType) Enum() *LifecycleType {
	p := new(LifecycleType)
	*p = x
	return p
}

func (x LifecycleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[4].Descriptor()
}

func (LifecycleType) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[4]
}

func (x LifecycleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleType.Descriptor instead.
func (LifecycleType) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[5].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[5]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

type ReportStatus int32

const (
	ReportStatus_REPORT_STATUS_UNSPECIFIED ReportStatus = 0
	ReportStatus_REPORT_STATUS_OK          ReportStatus = 1
	ReportStatus_REPORT_STATUS_ERROR       ReportStatus = 2
	ReportStatus_REPORT_STATUS_CANCELED    ReportStatus = 3
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_UNSPECIFIED",
		1: "REPORT_STATUS_OK",
		2: "REPORT_STATUS_ERROR",
		3: "REPORT_STATUS_CANCELED",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_UNSPECIFIED": 0,
		"REPORT_STATUS_OK":          1,
		"REPORT_STATUS_ERROR":       2,
		"REPORT_STATUS_CANCELED":    3,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_plugin_v1_plugin_proto_enumTypes[6].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_api_plugin_v1_plugin_proto_enumTypes[6]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ListPluginsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginMetadata      `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginMetadata {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type CreateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Config        []byte                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *CreateInstanceRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateInstanceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DestroyInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyInstanceRequest) Reset() {
	*x = DestroyInstanceRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyInstanceRequest) ProtoMessage() {}

func (x *DestroyInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyInstanceRequest.ProtoReflect.Descriptor instead.
func (*DestroyInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DestroyInstanceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DestroyInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyInstanceResponse) Reset() {
	*x = DestroyInstanceResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyInstanceResponse) ProtoMessage() {}

func (x *DestroyInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyInstanceResponse.ProtoReflect.Descriptor instead.
func (*DestroyInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

type PluginMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Schema        string                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Inputs        []*Property            `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*Property            `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Ports         []*PortMetadata        `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	MultiTrack    *MultiTrackConfig      `protobuf:"bytes,8,opt,name=multi_track,json=multiTrack,proto3" json:"multi_track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginMetadata) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PluginMetadata) GetInputs() []*Property {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PluginMetadata) GetOutputs() []*Property {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *PluginMetadata) GetPorts() []*PortMetadata {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *PluginMetadata) GetMultiTrack() *MultiTrackConfig {
	if x != nil {
		return x.MultiTrack
	}
	return nil
}

type MultiTrackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Payload       *TrackConfig           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTrackConfig) Reset() {
	*x = MultiTrackConfig{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTrackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTrackConfig) ProtoMessage() {}

func (x *MultiTrackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTrackConfig.ProtoReflect.Descriptor instead.
func (*MultiTrackConfig) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *MultiTrackConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MultiTrackConfig) GetPayload() *TrackConfig {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TrackConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BufferSize       int32                  `protobuf:"varint,2,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	DropStrategy     DropStrategy           `protobuf:"varint,3,opt,name=drop_strategy,json=dropStrategy,proto3,enum=plugin.v1.DropStrategy" json:"drop_strategy,omitempty"`
	InterruptSignals []string               `protobuf:"bytes,4,rep,name=interrupt_signals,json=interruptSignals,proto3" json:"interrupt_signals,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackConfig) Reset() {
	*x = TrackConfig{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackConfig) ProtoMessage() {}

func (x *TrackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackConfig.ProtoReflect.Descriptor instead.
func (*TrackConfig) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *TrackConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TrackConfig) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *TrackConfig) GetDropStrategy() DropStrategy {
	if x != nil {
		return x.DropStrategy
	}
	return DropStrategy_DROP_STRATEGY_UNSPECIFIED
}

func (x *TrackConfig) GetInterruptSignals() []string {
	if x != nil {
		return x.InterruptSignals
	}
	return nil
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.EventType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Property) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type          ValueType              `protobuf:"varint,2,opt,name=type,proto3,enum=plugin.v1.ValueType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *Field) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type PortMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.EventType" json:"type,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMetadata) Reset() {
	*x = PortMetadata{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMetadata) ProtoMessage() {}

func (x *PortMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMetadata.ProtoReflect.Descriptor instead.
func (*PortMetadata) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PortMetadata) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *PortMetadata) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RuntimeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Type          RuntimeMessageType     `protobuf:"varint,4,opt,name=type,proto3,enum=plugin.v1.RuntimeMessageType" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Body:
	//
	//	*RuntimeMessage_Lifecycle
	//	*RuntimeMessage_Signal
	//	*RuntimeMessage_Payload
	//	*RuntimeMessage_EmitSignal
	//	*RuntimeMessage_EmitPayload
	//	*RuntimeMessage_EmitLog
	//	*RuntimeMessage_Report
	//	*RuntimeMessage_Ack
	//	*RuntimeMessage_Cancel
	Body          isRuntimeMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeMessage) Reset() {
	*x = RuntimeMessage{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeMessage) ProtoMessage() {}

func (x *RuntimeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeMessage.ProtoReflect.Descriptor instead.
func (*RuntimeMessage) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *RuntimeMessage) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RuntimeMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RuntimeMessage) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RuntimeMessage) GetType() RuntimeMessageType {
	if x != nil {
		return x.Type
	}
	return RuntimeMessageType_RUNTIME_MESSAGE_TYPE_UNSPECIFIED
}

func (x *RuntimeMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RuntimeMessage) GetBody() isRuntimeMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RuntimeMessage) GetLifecycle() *LifecycleEvent {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Lifecycle); ok {
			return x.Lifecycle
		}
	}
	return nil
}

func (x *RuntimeMessage) GetSignal() *SignalEvent {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *RuntimeMessage) GetPayload() *PayloadEvent {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *RuntimeMessage) GetEmitSignal() *EmitSignal {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_EmitSignal); ok {
			return x.EmitSignal
		}
	}
	return nil
}

func (x *RuntimeMessage) GetEmitPayload() *EmitPayload {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_EmitPayload); ok {
			return x.EmitPayload
		}
	}
	return nil
}

func (x *RuntimeMessage) GetEmitLog() *EmitLog {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_EmitLog); ok {
			return x.EmitLog
		}
	}
	return nil
}

func (x *RuntimeMessage) GetReport() *EventReport {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *RuntimeMessage) GetAck() *EventAck {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RuntimeMessage) GetCancel() *CancelEvent {
	if x != nil {
		if x, ok := x.Body.(*RuntimeMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isRuntimeMessage_Body interface {
	isRuntimeMessage_Body()
}

type RuntimeMessage_Lifecycle struct {
	Lifecycle *LifecycleEvent `protobuf:"bytes,10,opt,name=lifecycle,proto3,oneof"`
}

type RuntimeMessage_Signal struct {
	Signal *SignalEvent `protobuf:"bytes,11,opt,name=signal,proto3,oneof"`
}

type RuntimeMessage_Payload struct {
	Payload *PayloadEvent `protobuf:"bytes,12,opt,name=payload,proto3,oneof"`
}

type RuntimeMessage_EmitSignal struct {
	EmitSignal *EmitSignal `protobuf:"bytes,13,opt,name=emit_signal,json=emitSignal,proto3,oneof"`
}

type RuntimeMessage_EmitPayload struct {
	EmitPayload *EmitPayload `protobuf:"bytes,14,opt,name=emit_payload,json=emitPayload,proto3,oneof"`
}

type RuntimeMessage_EmitLog struct {
	EmitLog *EmitLog `protobuf:"bytes,15,opt,name=emit_log,json=emitLog,proto3,oneof"`
}

type RuntimeMessage_Report struct {
	Report *EventReport `protobuf:"bytes,16,opt,name=report,proto3,oneof"`
}

type RuntimeMessage_Ack struct {
	Ack *EventAck `protobuf:"bytes,17,opt,name=ack,proto3,oneof"`
}

type RuntimeMessage_Cancel struct {
	Cancel *CancelEvent `protobuf:"bytes,18,opt,name=cancel,proto3,oneof"`
}

func (*RuntimeMessage_Lifecycle) isRuntimeMessage_Body() {}

func (*RuntimeMessage_Signal) isRuntimeMessage_Body() {}

func (*RuntimeMessage_Payload) isRuntimeMessage_Body() {}

func (*RuntimeMessage_EmitSignal) isRuntimeMessage_Body() {}

func (*RuntimeMessage_EmitPayload) isRuntimeMessage_Body() {}

func (*RuntimeMessage_EmitLog) isRuntimeMessage_Body() {}

func (*RuntimeMessage_Report) isRuntimeMessage_Body() {}

func (*RuntimeMessage_Ack) isRuntimeMessage_Body() {}

func (*RuntimeMessage_Cancel) isRuntimeMessage_Body() {}

type LifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LifecycleType          `protobuf:"varint,1,opt,name=type,proto3,enum=plugin.v1.LifecycleType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *LifecycleEvent) GetType() LifecycleType {
	if x != nil {
		return x.Type
	}
	return LifecycleType_LIFECYCLE_TYPE_UNSPECIFIED
}

type SignalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    []byte                 `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEvent) Reset() {
	*x = SignalEvent{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEvent) ProtoMessage() {}

func (x *SignalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEvent.ProtoReflect.Descriptor instead.
func (*SignalEvent) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *SignalEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalEvent) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PayloadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties    []byte                 `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadEvent) Reset() {
	*x = PayloadEvent{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadEvent) ProtoMessage() {}

func (x *PayloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadEvent.ProtoReflect.Descriptor instead.
func (*PayloadEvent) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *PayloadEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PayloadEvent) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

type EmitSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *SignalEvent           `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitSignal) Reset() {
	*x = EmitSignal{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitSignal) ProtoMessage() {}

func (x *EmitSignal) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitSignal.ProtoReflect.Descriptor instead.
func (*EmitSignal) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *EmitSignal) GetSignal() *SignalEvent {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *EmitSignal) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EmitPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PayloadEvent          `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitPayload) Reset() {
	*x = EmitPayload{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitPayload) ProtoMessage() {}

func (x *EmitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitPayload.ProtoReflect.Descriptor instead.
func (*EmitPayload) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *EmitPayload) GetPayload() *PayloadEvent {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EmitPayload) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EmitLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=plugin.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitLog) Reset() {
	*x = EmitLog{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitLog) ProtoMessage() {}

func (x *EmitLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitLog.ProtoReflect.Descriptor instead.
func (*EmitLog) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *EmitLog) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *EmitLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmitLog) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EventReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReportStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=plugin.v1.ReportStatus" json:"status,omitempty"`
	Error         *RemoteError           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReport) Reset() {
	*x = EventReport{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReport) ProtoMessage() {}

func (x *EventReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReport.ProtoReflect.Descriptor instead.
func (*EventReport) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *EventReport) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *EventReport) GetError() *RemoteError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoteError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteError) Reset() {
	*x = RemoteError{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteError) ProtoMessage() {}

func (x *RemoteError) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteError.ProtoReflect.Descriptor instead.
func (*RemoteError) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *RemoteError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RemoteError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoteError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *EventAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CancelEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelEvent) Reset() {
	*x = CancelEvent{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelEvent) ProtoMessage() {}

func (x *CancelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelEvent.ProtoReflect.Descriptor instead.
func (*CancelEvent) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

var File_api_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_api_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/plugin/v1/plugin.proto\x12\tplugin.v1\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"E\n" +
	"\fPingResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"2\n" +
	"\x12ListPluginsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"J\n" +
	"\x13ListPluginsResponse\x123\n" +
	"\aplugins\x18\x01 \x03(\v2\x19.plugin.v1.PluginMetadataR\aplugins\"\xfa\x01\n" +
	"\x15CreateInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..plugin.v1.CreateInstanceRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x16CreateInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"Q\n" +
	"\x16DestroyInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x19\n" +
	"\x17DestroyInstanceResponse\"\xa7\x02\n" +
	"\x0ePluginMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema\x12+\n" +
	"\x06inputs\x18\x05 \x03(\v2\x13.plugin.v1.PropertyR\x06inputs\x12-\n" +
	"\aoutputs\x18\x06 \x03(\v2\x13.plugin.v1.PropertyR\aoutputs\x12-\n" +
	"\x05ports\x18\a \x03(\v2\x17.plugin.v1.PortMetadataR\x05ports\x12<\n" +
	"\vmulti_track\x18\b \x01(\v2\x1b.plugin.v1.MultiTrackConfigR\n" +
	"multiTrack\"^\n" +
	"\x10MultiTrackConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x120\n" +
	"\apayload\x18\x02 \x01(\v2\x16.plugin.v1.TrackConfigR\apayload\"\xb3\x01\n" +
	"\vTrackConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vbuffer_size\x18\x02 \x01(\x05R\n" +
	"bufferSize\x12<\n" +
	"\rdrop_strategy\x18\x03 \x01(\x0e2\x17.plugin.v1.DropStrategyR\fdropStrategy\x12+\n" +
	"\x11interrupt_signals\x18\x04 \x03(\tR\x10interruptSignals\"r\n" +
	"\bProperty\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.plugin.v1.EventTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x06fields\x18\x03 \x03(\v2\x10.plugin.v1.FieldR\x06fields\"_\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.plugin.v1.ValueTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\x82\x01\n" +
	"\fPortMetadata\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.plugin.v1.EventTypeR\x04type\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8b\x06\n" +
	"\x0eRuntimeMessage\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.plugin.v1.RuntimeMessageTypeR\x04type\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.plugin.v1.RuntimeMessage.MetadataEntryR\bmetadata\x129\n" +
	"\tlifecycle\x18\n" +
	" \x01(\v2\x19.plugin.v1.LifecycleEventH\x00R\tlifecycle\x120\n" +
	"\x06signal\x18\v \x01(\v2\x16.plugin.v1.SignalEventH\x00R\x06signal\x123\n" +
	"\apayload\x18\f \x01(\v2\x17.plugin.v1.PayloadEventH\x00R\apayload\x128\n" +
	"\vemit_signal\x18\r \x01(\v2\x15.plugin.v1.EmitSignalH\x00R\n" +
	"emitSignal\x12;\n" +
	"\femit_payload\x18\x0e \x01(\v2\x16.plugin.v1.EmitPayloadH\x00R\vemitPayload\x12/\n" +
	"\bemit_log\x18\x0f \x01(\v2\x12.plugin.v1.EmitLogH\x00R\aemitLog\x120\n" +
	"\x06report\x18\x10 \x01(\v2\x16.plugin.v1.EventReportH\x00R\x06report\x12'\n" +
	"\x03ack\x18\x11 \x01(\v2\x13.plugin.v1.EventAckH\x00R\x03ack\x120\n" +
	"\x06cancel\x18\x12 \x01(\v2\x16.plugin.v1.CancelEventH\x00R\x06cancel\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04body\">\n" +
	"\x0eLifecycleEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.plugin.v1.LifecycleTypeR\x04type\"A\n" +
	"\vSignalEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"properties\x18\x02 \x01(\fR\n" +
	"properties\"B\n" +
	"\fPayloadEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"properties\x18\x02 \x01(\fR\n" +
	"properties\"P\n" +
	"\n" +
	"EmitSignal\x12.\n" +
	"\x06signal\x18\x01 \x01(\v2\x16.plugin.v1.SignalEventR\x06signal\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"T\n" +
	"\vEmitPayload\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.plugin.v1.PayloadEventR\apayload\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xc1\x01\n" +
	"\aEmitLog\x12)\n" +
	"\x05level\x18\x01 \x01(\x0e2\x13.plugin.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x06fields\x18\x03 \x03(\v2\x1e.plugin.v1.EmitLog.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\vEventReport\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.plugin.v1.ReportStatusR\x06status\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x16.plugin.v1.RemoteErrorR\x05error\"U\n" +
	"\vRemoteError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"(\n" +
	"\bEventAck\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\r\n" +
	"\vCancelEvent*\x8c\x01\n" +
	"\fDropStrategy\x12\x1d\n" +
	"\x19DROP_STRATEGY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDROP_STRATEGY_BLOCK_IF_FULL\x10\x01\x12\x1d\n" +
	"\x19DROP_STRATEGY_DROP_NEWEST\x10\x02\x12\x1d\n" +
	"\x19DROP_STRATEGY_DROP_OLDEST\x10\x03*\x82\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_SIGNAL\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_PAYLOAD\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_AUDIO\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_VIDEO\x10\x04*\xb2\x01\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VALUE_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11VALUE_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12VALUE_TYPE_INTEGER\x10\x03\x12\x16\n" +
	"\x12VALUE_TYPE_BOOLEAN\x10\x04\x12\x15\n" +
	"\x11VALUE_TYPE_OBJECT\x10\x05\x12\x14\n" +
	"\x10VALUE_TYPE_ARRAY\x10\x06*\xf1\x02\n" +
	"\x12RuntimeMessageType\x12$\n" +
	" RUNTIME_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRUNTIME_MESSAGE_TYPE_LIFECYCLE\x10\x01\x12\x1f\n" +
	"\x1bRUNTIME_MESSAGE_TYPE_SIGNAL\x10\x02\x12 \n" +
	"\x1cRUNTIME_MESSAGE_TYPE_PAYLOAD\x10\x03\x12$\n" +
	" RUNTIME_MESSAGE_TYPE_EMIT_SIGNAL\x10\x04\x12%\n" +
	"!RUNTIME_MESSAGE_TYPE_EMIT_PAYLOAD\x10\x05\x12!\n" +
	"\x1dRUNTIME_MESSAGE_TYPE_EMIT_LOG\x10\x06\x12\x1c\n" +
	"\x18RUNTIME_MESSAGE_TYPE_ACK\x10\a\x12\x1f\n" +
	"\x1bRUNTIME_MESSAGE_TYPE_REPORT\x10\b\x12\x1f\n" +
	"\x1bRUNTIME_MESSAGE_TYPE_CANCEL\x10\t*\xb1\x01\n" +
	"\rLifecycleType\x12\x1e\n" +
	"\x1aLIFECYCLE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LIFECYCLE_TYPE_START\x10\x01\x12\x18\n" +
	"\x14LIFECYCLE_TYPE_READY\x10\x02\x12\x18\n" +
	"\x14LIFECYCLE_TYPE_PAUSE\x10\x03\x12\x19\n" +
	"\x15LIFECYCLE_TYPE_RESUME\x10\x04\x12\x17\n" +
	"\x13LIFECYCLE_TYPE_STOP\x10\x05*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*x\n" +
	"\fReportStatus\x12\x1d\n" +
	"\x19REPORT_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REPORT_STATUS_OK\x10\x01\x12\x17\n" +
	"\x13REPORT_STATUS_ERROR\x10\x02\x12\x1a\n" +
	"\x16REPORT_STATUS_CANCELED\x10\x032\x96\x03\n" +
	"\x13RemotePluginService\x127\n" +
	"\x04Ping\x12\x16.plugin.v1.PingRequest\x1a\x17.plugin.v1.PingResponse\x12L\n" +
	"\vListPlugins\x12\x1d.plugin.v1.ListPluginsRequest\x1a\x1e.plugin.v1.ListPluginsResponse\x12U\n" +
	"\x0eCreateInstance\x12 .plugin.v1.CreateInstanceRequest\x1a!.plugin.v1.CreateInstanceResponse\x12X\n" +
	"\x0fDestroyInstance\x12!.plugin.v1.DestroyInstanceRequest\x1a\".plugin.v1.DestroyInstanceResponse\x12G\n" +
	"\vRunInstance\x12\x19.plugin.v1.RuntimeMessage\x1a\x19.plugin.v1.RuntimeMessage(\x010\x01B,Z*github.com/wnnce/voce/api/plugin/v1;pluginb\x06proto3"

var (
	file_api_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_api_plugin_v1_plugin_proto_rawDescData []byte
)

func file_api_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_api_plugin_v1_plugin_proto_rawDescData
}

var file_api_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_api_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_plugin_v1_plugin_proto_goTypes = []any{
	(DropStrategy)(0),               // 0: plugin.v1.DropStrategy
	(EventType)(0),                  // 1: plugin.v1.EventType
	(ValueType)(0),                  // 2: plugin.v1.ValueType
	(RuntimeMessageType)(0),         // 3: plugin.v1.RuntimeMessageType
	(LifecycleType)(0),              // 4: plugin.v1.LifecycleType
	(LogLevel)(0),                   // 5: plugin.v1.LogLevel
	(ReportStatus)(0),               // 6: plugin.v1.ReportStatus
	(*PingRequest)(nil),             // 7: plugin.v1.PingRequest
	(*PingResponse)(nil),            // 8: plugin.v1.PingResponse
	(*ListPluginsRequest)(nil),      // 9: plugin.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),     // 10: plugin.v1.ListPluginsResponse
	(*CreateInstanceRequest)(nil),   // 11: plugin.v1.CreateInstanceRequest
	(*CreateInstanceResponse)(nil),  // 12: plugin.v1.CreateInstanceResponse
	(*DestroyInstanceRequest)(nil),  // 13: plugin.v1.DestroyInstanceRequest
	(*DestroyInstanceResponse)(nil), // 14: plugin.v1.DestroyInstanceResponse
	(*PluginMetadata)(nil),          // 15: plugin.v1.PluginMetadata
	(*MultiTrackConfig)(nil),        // 16: plugin.v1.MultiTrackConfig
	(*TrackConfig)(nil),             // 17: plugin.v1.TrackConfig
	(*Property)(nil),                // 18: plugin.v1.Property
	(*Field)(nil),                   // 19: plugin.v1.Field
	(*PortMetadata)(nil),            // 20: plugin.v1.PortMetadata
	(*RuntimeMessage)(nil),          // 21: plugin.v1.RuntimeMessage
	(*LifecycleEvent)(nil),          // 22: plugin.v1.LifecycleEvent
	(*SignalEvent)(nil),             // 23: plugin.v1.SignalEvent
	(*PayloadEvent)(nil),            // 24: plugin.v1.PayloadEvent
	(*EmitSignal)(nil),              // 25: plugin.v1.EmitSignal
	(*EmitPayload)(nil),             // 26: plugin.v1.EmitPayload
	(*EmitLog)(nil),                 // 27: plugin.v1.EmitLog
	(*EventReport)(nil),             // 28: plugin.v1.EventReport
	(*RemoteError)(nil),             // 29: plugin.v1.RemoteError
	(*EventAck)(nil),                // 30: plugin.v1.EventAck
	(*CancelEvent)(nil),             // 31: plugin.v1.CancelEvent
	nil,                             // 32: plugin.v1.CreateInstanceRequest.MetadataEntry
	nil,                             // 33: plugin.v1.RuntimeMessage.MetadataEntry
	nil,                             // 34: plugin.v1.EmitLog.FieldsEntry
}
var file_api_plugin_v1_plugin_proto_depIdxs = []int32{
	15, // 0: plugin.v1.ListPluginsResponse.plugins:type_name -> plugin.v1.PluginMetadata
	32, // 1: plugin.v1.CreateInstanceRequest.metadata:type_name -> plugin.v1.CreateInstanceRequest.MetadataEntry
	18, // 2: plugin.v1.PluginMetadata.inputs:type_name -> plugin.v1.Property
	18, // 3: plugin.v1.PluginMetadata.outputs:type_name -> plugin.v1.Property
	20, // 4: plugin.v1.PluginMetadata.ports:type_name -> plugin.v1.PortMetadata
	16, // 5: plugin.v1.PluginMetadata.multi_track:type_name -> plugin.v1.MultiTrackConfig
	17, // 6: plugin.v1.MultiTrackConfig.payload:type_name -> plugin.v1.TrackConfig
	0,  // 7: plugin.v1.TrackConfig.drop_strategy:type_name -> plugin.v1.DropStrategy
	1,  // 8: plugin.v1.Property.type:type_name -> plugin.v1.EventType
	19, // 9: plugin.v1.Property.fields:type_name -> plugin.v1.Field
	2,  // 10: plugin.v1.Field.type:type_name -> plugin.v1.ValueType
	1,  // 11: plugin.v1.PortMetadata.type:type_name -> plugin.v1.EventType
	3,  // 12: plugin.v1.RuntimeMessage.type:type_name -> plugin.v1.RuntimeMessageType
	33, // 13: plugin.v1.RuntimeMessage.metadata:type_name -> plugin.v1.RuntimeMessage.MetadataEntry
	22, // 14: plugin.v1.RuntimeMessage.lifecycle:type_name -> plugin.v1.LifecycleEvent
	23, // 15: plugin.v1.RuntimeMessage.signal:type_name -> plugin.v1.SignalEvent
	24, // 16: plugin.v1.RuntimeMessage.payload:type_name -> plugin.v1.PayloadEvent
	25, // 17: plugin.v1.RuntimeMessage.emit_signal:type_name -> plugin.v1.EmitSignal
	26, // 18: plugin.v1.RuntimeMessage.emit_payload:type_name -> plugin.v1.EmitPayload
	27, // 19: plugin.v1.RuntimeMessage.emit_log:type_name -> plugin.v1.EmitLog
	28, // 20: plugin.v1.RuntimeMessage.report:type_name -> plugin.v1.EventReport
	30, // 21: plugin.v1.RuntimeMessage.ack:type_name -> plugin.v1.EventAck
	31, // 22: plugin.v1.RuntimeMessage.cancel:type_name -> plugin.v1.CancelEvent
	4,  // 23: plugin.v1.LifecycleEvent.type:type_name -> plugin.v1.LifecycleType
	23, // 24: plugin.v1.EmitSignal.signal:type_name -> plugin.v1.SignalEvent
	24, // 25: plugin.v1.EmitPayload.payload:type_name -> plugin.v1.PayloadEvent
	5,  // 26: plugin.v1.EmitLog.level:type_name -> plugin.v1.LogLevel
	34, // 27: plugin.v1.EmitLog.fields:type_name -> plugin.v1.EmitLog.FieldsEntry
	6,  // 28: plugin.v1.EventReport.status:type_name -> plugin.v1.ReportStatus
	29, // 29: plugin.v1.EventReport.error:type_name -> plugin.v1.RemoteError
	7,  // 30: plugin.v1.RemotePluginService.Ping:input_type -> plugin.v1.PingRequest
	9,  // 31: plugin.v1.RemotePluginService.ListPlugins:input_type -> plugin.v1.ListPluginsRequest
	11, // 32: plugin.v1.RemotePluginService.CreateInstance:input_type -> plugin.v1.CreateInstanceRequest
	13, // 33: plugin.v1.RemotePluginService.DestroyInstance:input_type -> plugin.v1.DestroyInstanceRequest
	21, // 34: plugin.v1.RemotePluginService.RunInstance:input_type -> plugin.v1.RuntimeMessage
	8,  // 35: plugin.v1.RemotePluginService.Ping:output_type -> plugin.v1.PingResponse
	10, // 36: plugin.v1.RemotePluginService.ListPlugins:output_type -> plugin.v1.ListPluginsResponse
	12, // 37: plugin.v1.RemotePluginService.CreateInstance:output_type -> plugin.v1.CreateInstanceResponse
	14, // 38: plugin.v1.RemotePluginService.DestroyInstance:output_type -> plugin.v1.DestroyInstanceResponse
	21, // 39: plugin.v1.RemotePluginService.RunInstance:output_type -> plugin.v1.RuntimeMessage
	35, // [35:40] is the sub-list for method output_type
	30, // [30:35] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_api_plugin_v1_plugin_proto_init() }
func file_api_plugin_v1_plugin_proto_init() {
	if File_api_plugin_v1_plugin_proto != nil {
		return
	}
	file_api_plugin_v1_plugin_proto_msgTypes[14].OneofWrappers = []any{
		(*RuntimeMessage_Lifecycle)(nil),
		(*RuntimeMessage_Signal)(nil),
		(*RuntimeMessage_Payload)(nil),
		(*RuntimeMessage_EmitSignal)(nil),
		(*RuntimeMessage_EmitPayload)(nil),
		(*RuntimeMessage_EmitLog)(nil),
		(*RuntimeMessage_Report)(nil),
		(*RuntimeMessage_Ack)(nil),
		(*RuntimeMessage_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_api_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_api_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_plugin_v1_plugin_proto = out.File
	file_api_plugin_v1_plugin_proto_goTypes = nil
	file_api_plugin_v1_plugin_proto_depIdxs = nil
}
