# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from voce.proto import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemotePluginServiceStub:
    """RemotePluginService is implemented by a remote plugin server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/plugin.v1.RemotePluginService/Ping',
                request_serializer=plugin__pb2.PingRequest.SerializeToString,
                response_deserializer=plugin__pb2.PingResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/plugin.v1.RemotePluginService/ListPlugins',
                request_serializer=plugin__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=plugin__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.CreateInstance = channel.unary_unary(
                '/plugin.v1.RemotePluginService/CreateInstance',
                request_serializer=plugin__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=plugin__pb2.CreateInstanceResponse.FromString,
                _registered_method=True)
        self.DestroyInstance = channel.unary_unary(
                '/plugin.v1.RemotePluginService/DestroyInstance',
                request_serializer=plugin__pb2.DestroyInstanceRequest.SerializeToString,
                response_deserializer=plugin__pb2.DestroyInstanceResponse.FromString,
                _registered_method=True)
        self.RunInstance = channel.stream_stream(
                '/plugin.v1.RemotePluginService/RunInstance',
                request_serializer=plugin__pb2.RuntimeMessage.SerializeToString,
                response_deserializer=plugin__pb2.RuntimeMessage.FromString,
                _registered_method=True)


class RemotePluginServiceServicer:
    """RemotePluginService is implemented by a remote plugin server.
    """

    def Ping(self, request, context):
        """Ping is a lightweight unary heartbeat request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """ListPlugins returns plugin metadata exposed by the remote plugin server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInstance(self, request, context):
        """CreateInstance creates one plugin instance for a workflow node/session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyInstance(self, request, context):
        """DestroyInstance releases a previously created plugin instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunInstance(self, request_iterator, context):
        """RunInstance is the dedicated bidirectional event stream for one plugin instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemotePluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=plugin__pb2.PingRequest.FromString,
                    response_serializer=plugin__pb2.PingResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=plugin__pb2.ListPluginsRequest.FromString,
                    response_serializer=plugin__pb2.ListPluginsResponse.SerializeToString,
            ),
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=plugin__pb2.CreateInstanceRequest.FromString,
                    response_serializer=plugin__pb2.CreateInstanceResponse.SerializeToString,
            ),
            'DestroyInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyInstance,
                    request_deserializer=plugin__pb2.DestroyInstanceRequest.FromString,
                    response_serializer=plugin__pb2.DestroyInstanceResponse.SerializeToString,
            ),
            'RunInstance': grpc.stream_stream_rpc_method_handler(
                    servicer.RunInstance,
                    request_deserializer=plugin__pb2.RuntimeMessage.FromString,
                    response_serializer=plugin__pb2.RuntimeMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plugin.v1.RemotePluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plugin.v1.RemotePluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemotePluginService:
    """RemotePluginService is implemented by a remote plugin server.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.v1.RemotePluginService/Ping',
            plugin__pb2.PingRequest.SerializeToString,
            plugin__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.v1.RemotePluginService/ListPlugins',
            plugin__pb2.ListPluginsRequest.SerializeToString,
            plugin__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.v1.RemotePluginService/CreateInstance',
            plugin__pb2.CreateInstanceRequest.SerializeToString,
            plugin__pb2.CreateInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.v1.RemotePluginService/DestroyInstance',
            plugin__pb2.DestroyInstanceRequest.SerializeToString,
            plugin__pb2.DestroyInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunInstance(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/plugin.v1.RemotePluginService/RunInstance',
            plugin__pb2.RuntimeMessage.SerializeToString,
            plugin__pb2.RuntimeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
