package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedFileName = "init_gen.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	pluginsDir, err := os.Getwd()
	if err != nil {
		return err
	}
	repoRoot, modulePath, err := findModule(pluginsDir)
	if err != nil {
		return err
	}
	imports, err := registeredPluginImports(repoRoot, modulePath, pluginsDir)
	if err != nil {
		return err
	}
	return writeGeneratedFile(filepath.Join(pluginsDir, generatedFileName), imports)
}

func findModule(start string) (string, string, error) {
	dir := start
	for {
		goMod := filepath.Join(dir, "go.mod")
		data, err := os.ReadFile(goMod)
		if err == nil {
			modulePath, pErr := parseModulePath(data)
			if pErr != nil {
				return "", "", pErr
			}
			return dir, modulePath, nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", "", err
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func parseModulePath(goMod []byte) (string, error) {
	for _, line := range bytes.Split(goMod, []byte{'\n'}) {
		fields := strings.Fields(string(line))
		if len(fields) >= 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", errors.New("module path not found in go.mod")
}

func registeredPluginImports(repoRoot, modulePath, pluginsDir string) ([]string, error) {
	entries, err := os.ReadDir(pluginsDir)
	if err != nil {
		return nil, err
	}
	var imports []string
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || strings.HasPrefix(entry.Name(), "_") {
			continue
		}
		dir := filepath.Join(pluginsDir, entry.Name())
		ok, err := containsPluginRegistration(dir)
		if err != nil {
			return nil, err
		}
		if !ok {
			continue
		}
		rel, err := filepath.Rel(repoRoot, dir)
		if err != nil {
			return nil, err
		}
		imports = append(imports, modulePath+"/"+filepath.ToSlash(rel))
	}
	sort.Strings(imports)
	return imports, nil
}

func containsPluginRegistration(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		ok, err := fileContainsPluginRegistration(path)
		if err != nil {
			return false, err
		}
		if ok {
			return true, nil
		}
	}
	return false, nil
}

func fileContainsPluginRegistration(path string) (bool, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return false, err
	}
	found := false
	ast.Inspect(file, func(node ast.Node) bool {
		if found {
			return false
		}
		call, ok := node.(*ast.CallExpr)
		if !ok {
			return true
		}
		fun := call.Fun
		if index, aok := fun.(*ast.IndexExpr); aok {
			fun = index.X
		}
		if index, aok := fun.(*ast.IndexListExpr); aok {
			fun = index.X
		}
		sel, ok := fun.(*ast.SelectorExpr)
		if !ok || sel.Sel.Name != "RegisterPlugin" {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok || ident.Name != "engine" {
			return true
		}
		found = true
		return false
	})
	return found, nil
}

func writeGeneratedFile(path string, imports []string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("package plugins\n\n")
	buf.WriteString("import (\n")
	for _, importPath := range imports {
		fmt.Fprintf(&buf, "\t_ %q\n", importPath)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}
