// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: api/voce/v1/voce.proto

package voce

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoceService_RealtimeStream_FullMethodName = "/voce.v1.VoceService/RealtimeStream"
)

// VoceServiceClient is the client API for VoceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoceServiceClient interface {
	// RealtimeStream is a bidirectional streaming RPC for audio and control messages
	RealtimeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error)
}

type voceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoceServiceClient(cc grpc.ClientConnInterface) VoceServiceClient {
	return &voceServiceClient{cc}
}

func (c *voceServiceClient) RealtimeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Packet, Packet], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoceService_ServiceDesc.Streams[0], VoceService_RealtimeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Packet, Packet]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoceService_RealtimeStreamClient = grpc.BidiStreamingClient[Packet, Packet]

// VoceServiceServer is the server API for VoceService service.
// All implementations must embed UnimplementedVoceServiceServer
// for forward compatibility.
type VoceServiceServer interface {
	// RealtimeStream is a bidirectional streaming RPC for audio and control messages
	RealtimeStream(grpc.BidiStreamingServer[Packet, Packet]) error
	mustEmbedUnimplementedVoceServiceServer()
}

// UnimplementedVoceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoceServiceServer struct{}

func (UnimplementedVoceServiceServer) RealtimeStream(grpc.BidiStreamingServer[Packet, Packet]) error {
	return status.Error(codes.Unimplemented, "method RealtimeStream not implemented")
}
func (UnimplementedVoceServiceServer) mustEmbedUnimplementedVoceServiceServer() {}
func (UnimplementedVoceServiceServer) testEmbeddedByValue()                     {}

// UnsafeVoceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoceServiceServer will
// result in compilation errors.
type UnsafeVoceServiceServer interface {
	mustEmbedUnimplementedVoceServiceServer()
}

func RegisterVoceServiceServer(s grpc.ServiceRegistrar, srv VoceServiceServer) {
	// If the following call panics, it indicates UnimplementedVoceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoceService_ServiceDesc, srv)
}

func _VoceService_RealtimeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoceServiceServer).RealtimeStream(&grpc.GenericServerStream[Packet, Packet]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoceService_RealtimeStreamServer = grpc.BidiStreamingServer[Packet, Packet]

// VoceService_ServiceDesc is the grpc.ServiceDesc for VoceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voce.v1.VoceService",
	HandlerType: (*VoceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RealtimeStream",
			Handler:       _VoceService_RealtimeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/voce/v1/voce.proto",
}
