// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/voce/v1/voce.proto

package voce

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PacketEncode maps to internal/protocol/packet.go PacketEncode
type PacketEncode int32

const (
	PacketEncode_ENCODE_RAW  PacketEncode = 0
	PacketEncode_ENCODE_JSON PacketEncode = 1
)

// Enum value maps for PacketEncode.
var (
	PacketEncode_name = map[int32]string{
		0: "ENCODE_RAW",
		1: "ENCODE_JSON",
	}
	PacketEncode_value = map[string]int32{
		"ENCODE_RAW":  0,
		"ENCODE_JSON": 1,
	}
)

func (x PacketEncode) Enum() *PacketEncode {
	p := new(PacketEncode)
	*p = x
	return p
}

func (x PacketEncode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketEncode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_voce_v1_voce_proto_enumTypes[0].Descriptor()
}

func (PacketEncode) Type() protoreflect.EnumType {
	return &file_api_voce_v1_voce_proto_enumTypes[0]
}

func (x PacketEncode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketEncode.Descriptor instead.
func (PacketEncode) EnumDescriptor() ([]byte, []int) {
	return file_api_voce_v1_voce_proto_rawDescGZIP(), []int{0}
}

// PacketType maps to internal/protocol/packet.go PacketType
type PacketType int32

const (
	PacketType_TYPE_UNKNOWN            PacketType = 0
	PacketType_TYPE_AUDIO              PacketType = 1
	PacketType_TYPE_ERROR              PacketType = 2
	PacketType_TYPE_TEXT               PacketType = 3
	PacketType_TYPE_CLOSE              PacketType = 4
	PacketType_TYPE_INTERRUPTER        PacketType = 17 // 0x11
	PacketType_TYPE_CAPTION            PacketType = 18 // 0x12
	PacketType_TYPE_USER_SPEECH_START  PacketType = 19 // 0x13
	PacketType_TYPE_USER_SPEECH_END    PacketType = 20 // 0x14
	PacketType_TYPE_AGENT_SPEECH_START PacketType = 21 // 0x15
	PacketType_TYPE_AGENT_SPEECH_END   PacketType = 22 // 0x16
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0:  "TYPE_UNKNOWN",
		1:  "TYPE_AUDIO",
		2:  "TYPE_ERROR",
		3:  "TYPE_TEXT",
		4:  "TYPE_CLOSE",
		17: "TYPE_INTERRUPTER",
		18: "TYPE_CAPTION",
		19: "TYPE_USER_SPEECH_START",
		20: "TYPE_USER_SPEECH_END",
		21: "TYPE_AGENT_SPEECH_START",
		22: "TYPE_AGENT_SPEECH_END",
	}
	PacketType_value = map[string]int32{
		"TYPE_UNKNOWN":            0,
		"TYPE_AUDIO":              1,
		"TYPE_ERROR":              2,
		"TYPE_TEXT":               3,
		"TYPE_CLOSE":              4,
		"TYPE_INTERRUPTER":        17,
		"TYPE_CAPTION":            18,
		"TYPE_USER_SPEECH_START":  19,
		"TYPE_USER_SPEECH_END":    20,
		"TYPE_AGENT_SPEECH_START": 21,
		"TYPE_AGENT_SPEECH_END":   22,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_voce_v1_voce_proto_enumTypes[1].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_api_voce_v1_voce_proto_enumTypes[1]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_api_voce_v1_voce_proto_rawDescGZIP(), []int{1}
}

// Packet is the message structure for bidirectional streaming
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PacketType             `protobuf:"varint,1,opt,name=type,proto3,enum=voce.v1.PacketType" json:"type,omitempty"`
	Encode        PacketEncode           `protobuf:"varint,2,opt,name=encode,proto3,enum=voce.v1.PacketEncode" json:"encode,omitempty"` // Mapping internal/protocol PacketEncode
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_api_voce_v1_voce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_api_voce_v1_voce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_api_voce_v1_voce_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_TYPE_UNKNOWN
}

func (x *Packet) GetEncode() PacketEncode {
	if x != nil {
		return x.Encode
	}
	return PacketEncode_ENCODE_RAW
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_voce_v1_voce_proto protoreflect.FileDescriptor

const file_api_voce_v1_voce_proto_rawDesc = "" +
	"\n" +
	"\x16api/voce/v1/voce.proto\x12\avoce.v1\"\xf2\x01\n" +
	"\x06Packet\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.voce.v1.PacketTypeR\x04type\x12-\n" +
	"\x06encode\x18\x02 \x01(\x0e2\x15.voce.v1.PacketEncodeR\x06encode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x129\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1d.voce.v1.Packet.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*/\n" +
	"\fPacketEncode\x12\x0e\n" +
	"\n" +
	"ENCODE_RAW\x10\x00\x12\x0f\n" +
	"\vENCODE_JSON\x10\x01*\xf3\x01\n" +
	"\n" +
	"PacketType\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_AUDIO\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x02\x12\r\n" +
	"\tTYPE_TEXT\x10\x03\x12\x0e\n" +
	"\n" +
	"TYPE_CLOSE\x10\x04\x12\x14\n" +
	"\x10TYPE_INTERRUPTER\x10\x11\x12\x10\n" +
	"\fTYPE_CAPTION\x10\x12\x12\x1a\n" +
	"\x16TYPE_USER_SPEECH_START\x10\x13\x12\x18\n" +
	"\x14TYPE_USER_SPEECH_END\x10\x14\x12\x1b\n" +
	"\x17TYPE_AGENT_SPEECH_START\x10\x15\x12\x19\n" +
	"\x15TYPE_AGENT_SPEECH_END\x10\x162E\n" +
	"\vVoceService\x126\n" +
	"\x0eRealtimeStream\x12\x0f.voce.v1.Packet\x1a\x0f.voce.v1.Packet(\x010\x01B(Z&github.com/wnnce/voce/api/voce/v1;voceb\x06proto3"

var (
	file_api_voce_v1_voce_proto_rawDescOnce sync.Once
	file_api_voce_v1_voce_proto_rawDescData []byte
)

func file_api_voce_v1_voce_proto_rawDescGZIP() []byte {
	file_api_voce_v1_voce_proto_rawDescOnce.Do(func() {
		file_api_voce_v1_voce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_voce_v1_voce_proto_rawDesc), len(file_api_voce_v1_voce_proto_rawDesc)))
	})
	return file_api_voce_v1_voce_proto_rawDescData
}

var file_api_voce_v1_voce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_voce_v1_voce_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_voce_v1_voce_proto_goTypes = []any{
	(PacketEncode)(0), // 0: voce.v1.PacketEncode
	(PacketType)(0),   // 1: voce.v1.PacketType
	(*Packet)(nil),    // 2: voce.v1.Packet
	nil,               // 3: voce.v1.Packet.MetadataEntry
}
var file_api_voce_v1_voce_proto_depIdxs = []int32{
	1, // 0: voce.v1.Packet.type:type_name -> voce.v1.PacketType
	0, // 1: voce.v1.Packet.encode:type_name -> voce.v1.PacketEncode
	3, // 2: voce.v1.Packet.metadata:type_name -> voce.v1.Packet.MetadataEntry
	2, // 3: voce.v1.VoceService.RealtimeStream:input_type -> voce.v1.Packet
	2, // 4: voce.v1.VoceService.RealtimeStream:output_type -> voce.v1.Packet
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_voce_v1_voce_proto_init() }
func file_api_voce_v1_voce_proto_init() {
	if File_api_voce_v1_voce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_voce_v1_voce_proto_rawDesc), len(file_api_voce_v1_voce_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_voce_v1_voce_proto_goTypes,
		DependencyIndexes: file_api_voce_v1_voce_proto_depIdxs,
		EnumInfos:         file_api_voce_v1_voce_proto_enumTypes,
		MessageInfos:      file_api_voce_v1_voce_proto_msgTypes,
	}.Build()
	File_api_voce_v1_voce_proto = out.File
	file_api_voce_v1_voce_proto_goTypes = nil
	file_api_voce_v1_voce_proto_depIdxs = nil
}
