name: Setup Web Environment
description: Installs Node, pnpm and web dependencies
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install Web Deps
      shell: bash
      run: cd clients/web && pnpm install
