name: Voce CI

on:
  push:
    branches: &branches
      - main
      - test
      - dev
      - "feature/*"
      - "release/*"
      - "fix/*"
  pull_request:
    branches: *branches

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Backend Environment
        uses: ./.github/actions/setup-backend
      - name: Backend Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  lint-web:
    name: Lint Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Web Environment
        uses: ./.github/actions/setup-web
      - name: Web Lint
        run: make lint-web

  lint-tui:
    name: Lint TUI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup TUI Environment
        uses: ./.github/actions/setup-tui
      - name: TUI Lint
        run: make lint-tui

  test-backend:
    name: Test Backend
    needs: [lint-backend, lint-web, lint-tui]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Backend Environment
        uses: ./.github/actions/setup-backend
      - name: Backend Test
        run: make test-backend

  test-tui:
    name: Test TUI
    needs: [lint-backend, lint-web, lint-tui]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup TUI Environment
        uses: ./.github/actions/setup-tui
      - name: TUI Test
        run: make test-tui
